### ISSUE TITLE
PackagesNotFoundError: numpy==1.13.0

### ISSUE THREAD

**Issue by PatrickLYTang** [DevelopmentalImagingMCRI/karawun#12]
Hi,

When creating a conda environment I encounter a PackagesNotFoundError for numpy 1.13.0. Do you have any suggestions or experience with this error (in conda list numpy 1.17.0 is listed)?

Regards, Patrick

![PackagesNotFoundError](https://user-images.githubusercontent.com/78799311/107363440-726b9500-6ada-11eb-8371-5f58edf0cd44.JPG)

**Comment by richardbeare** [comment]
The same command still works on a mac. I'll attempt the same test under windows in the office. At the moment I can only suggest looking for more channels - `conda search numpy` to see what shows up.

It probably means that it is time to bump versions of dependencies, possibly when the next SimpleITK is frozen.

**Comment by richardbeare** [comment]
Hi,
I have a test version for you to try:

```
conda create --name KarawunEnv --file https://github.com/richardbeare/karawun/raw/NumpyDep/requirements.txt
conda activate KarawunEnv
pip install git+https://github.com/richardbeare/karawun.git@NumpyDep

```
If this does successfully install, I'd strongly recommending running the tests, as I've only done so under Linux.

Do the following with the KarawunEnv activated:

```
git clone https://github.com/richardbeare/karawun.git --branch NumpyDep
cd karawun
python -m pytest -s tests/

```
Hopefully they will all pass...

**Comment by PatrickLYTang** [comment]
Hi Richard,

Thanks a lot for the quick response. The installation of Karawun was successful! Unfortunately, parts of the tests raise an AssertionError. Do you have a suggestion what might be the cause?

Thanks in advance,

Patrick

![image](https://user-images.githubusercontent.com/78799311/107665656-f3b75900-6c8d-11eb-9f64-0080e3d335a4.png)

**Comment by richardbeare** [comment]
I confirm the same failures under windows. This will take a little time to sort out. Hopefully it isn't anything dramatic. The files appear to get created, so you can have a play around importing to brainlab, but please don't do anything serious with the results for the moment.

**Comment by richardbeare** [comment]
Good news! The problem related to the test framework under windows (I was careless with paths, and the errors in the screenshot show different strings in the dictionary keys).

Add `--upgrade --force-reinstall` to your pip command, and retest. Alternatively you could do a "git pull" in the copy you cloned and install that. Let me know if it works and I'll merge into master.

**Comment by PatrickLYTang** [comment]
Hi Richard,

Thanks a lot! Indeed, there were no failures during the testing phase.

Regards,

Patrick
