### ISSUE TITLE
empty label file

### ISSUE THREAD

**Issue by LucSam** [DevelopmentalImagingMCRI/karawun#2]
Hi, when we export labels, such as a ROI, we get an empty file, it's not visible in Brainlab.
The crosshairs however indicate the right position though.
The ROI is based on a T1 which has been provided as a nii file to the command. It works fine for the tracts.
Do you have a suggestion how to overcome that problem?

Best, Lucius

`importTractography --dicom-template path/to/dicom/slice.dcm --nifti t1.nii.gz fa.nii.gz ROI.nii.gz --tract-files tract.tck --label-files ROI.nii.gz -o .`

**Comment by richardbeare** [comment]
Thanks for the test - can you send the samples for debugging?

A couple of thoughts. I have noticed that some label files, with lots of different labels, can take a while for brainlab to convert. The other possibility is that the label value is too high - currently it only supports values up to 30.

Also, I haven't tested using the same image in both the --nifti and the --label-files option. If ROI.nii.gz is derived from t1.nii.gz, then the following is meant to work:
```bash
importTractography --dicom-template path/to/dicom/slice.dcm --nifti t1.nii.gz fa.nii.gz  --tract-files tract.tck --label-files ROI.nii.gz -o ./Patient/
```

**Comment by LucSam** [comment]
Thank you very much, we detected the issue which occurred by a brainlab employee by anonymising the data.

**Comment by richardbeare** [comment]
Confirming - you see what you expect to see in brainlab? If so I will create an official release for this point.

**Comment by LucSam** [comment]
> Confirming - you see what you expect to see in brainlab? If so I will create an official release for this point.

Yes, I can confirm that it works

**Comment by richardbeare** [comment]
Thanks. I will tag the release tomorrow.
