### ISSUE TITLE
Double check and fMRI pipeline

### ISSUE THREAD

**Issue by BMdCTools** [DevelopmentalImagingMCRI/karawun#29]
Dear developers,

I am intended to use Karawun to include tractography and fMRI post-processed data in our BrainLab Neuronavegator. 
For MRTrix tractography, the example is clear, and I have no concerns about formats and conversion. For fMRI, I have some questions I would like to verify:
1 - Our processing pipeline for fMRI is done in SPM12. We can do all the steps in the subject's native space, with the fMRIs and derived results registered (linearly) to the T1WI. What kind of image is the safest option to use as a result: Threshold or 'unthresholded' (to be thresholded at NN) statistical maps?

2 - What is your recommended initial conversion tool to convert images from DICOM to NIfTI? We usually use Chris Rorden DCM2NII. Is that fine?

3 - Understandably, the original DICOM image should be included as a metadata donor. At UNICAMP, most of the fMRI data are exported in NIfTI from the scanner. How critical is the data imported from this donor (standard orientation, dimensions and etc... or very subject-specific information)? Could I use a generic donor (same acquisition protocol) DICOM file for all cases in which I only have NIfTI files?

Thanks!

**Comment by richardbeare** [comment]
Hi,
Thanks for your interest in Karawun.
1. You are welcome to use both thresholded and unthresholded, with thresholded images being passed using the `--label-files` option (see https://developmentalimagingmcri.github.io/karawun/using.html). You then have the option of comparing the two in Brainlab.
We find that choice depends on audience, with surgeons, for example, preferring to see thresholded results. The display options in Brainlab are also different for thresholded results, with better 3D options available.
2. We use both dcm2niix and mrconvert (from mrtrix). It basically doesn't matter provided that you're confident in the results and that your processing pipeline produces appropriately formatted nifti (especially wrt orientation matrices). The test of this is viewing with mrview. If the image/tract set you've produced can be displayed in mrview and overlays and aligns as you expect then the result in Brainlab will be the same.
3. The dicom template copies mostly non-image meta data - e.g. patient name etc. There is nothing about orientation, image size etc (meaning that your processing pipeline can change all of these things as much as you like). All the image information is derived from the nifti. A generic donor (or the data shipped with Karawun) will work. The problem will be in distinguishing multiple patients once you import them. A simple option will be to use an anonymisation tool (e.g. gdcmanon) to change those fields to something useful (e.g. patient study IDs).

Good luck!

**Comment by richardbeare** [comment]
Hi,
Another thing to consider if providing unthresholded maps. Karawun doesn't do any scaling of data, so you should prescale your floating point t or p-val maps to something that makes sense with integer values - e.g. multiply by 1000.

**Comment by BMdCTools** [comment]
> Hi, Another thing to consider if providing unthresholded maps. Karawun doesn't do any scaling of data, so you should prescale your floating point t or p-val maps to something that makes sense with integer values - e.g. multiply by 1000.

Dear Richard,
Thank you very much for the precise and clear answers. I will start using Karawun as soon as possible.
Best regards,
