### ISSUE TITLE
How to view converted files in mrview or any other viewer

### ISSUE THREAD

**Issue by nayanw775** [DevelopmentalImagingMCRI/karawun#30]
Dear Karawun Developers,

I am trying to use the Karawun for conversion of tracts to dicom for navigation systems, but before viewing it into navigation how can I view them locally using any viewer, I tried slicer and mrview, both are not working below is my command
importTractography -d (giving the header file) -n T1.nii.gz -t optic_radiation.tck -o /path/to/output

Tracts got converted into dicom, but I am unable to view them

**Comment by richardbeare** [comment]
Hi,
Thanks for your interest.
The results of converting the T1.nii.gz file will almost certainly be viewable in mrview, but none of the other forms will. Brainlab is the only product we are aware of that will view that specific dicom modality (SEG mode that isn't voxel based). Our usual practice is to compare the view in brainlab to the view of the input tck file in mrview.
Hope this helps
