### ISSUE TITLE
importTractography -h throws an error

### ISSUE THREAD

**Issue by Redzerman** [DevelopmentalImagingMCRI/karawun#6]
Hi there, 
i successfully installed Karawun as per steps 1-5 here: https://github.com/DevelopmentalImagingMCRI/karawun

However when i run importTractography -h I get the following error:
![image](https://user-images.githubusercontent.com/10850810/71724347-e6436480-2e27-11ea-90b8-b7e9a243ea11.png)

Any ideas?

Thanks in advance.

**Comment by richardbeare** [comment]
This appears to be an error from Windows. I have not yet tested Karawun under Windows, but will do so and get back to you. The error is saying that the Windows shell you are using can't find the main karawun script. The obvious checks to make are to ensure that the cmd shell from which you are attempting to run importTractography has the miniconda environment activated. 

I've done a bit more reading - seems that some restructuring of the package scripts will be needed for windows compatibility.

**Comment by richardbeare** [comment]
It may not have been as tricky as before. Please check updated instructions at:
https://github.com/richardbeare/karawun/tree/WindowsScripts

and use the following install command
```bash
pip install git+https://github.com/richardbeare/karawun.git@WindowsScripts
```

The main changes I've made to the instructions include removing linebreaks that prevent pasting the commands into a windows terminal and a git installation step. You may have already fixed those problems on your own.

Let me know if it works for you. I'll merge it into the main distribution if it does.

**Comment by Redzerman** [comment]
Hi there,
I have successfully installed karawun using the updated steps catered for windows as above. Running importTractography -h returns the expected output, I have not tried to convert .tck files yet but once i'm in a positon to do so and if i run into problems I will report back. Thanks for your help.

Just to note , with the original installation method the help info could be returned by moving to C:\Users\<USER>\karawun\bin and initialising python in the powershell with the following command:
 `python importTractography -h`

However i'm not yet sure if this will successfully perform the conversion but i expect it should.

Thanks again.
